<a href="https://colab.research.google.com/github/AgudeloKimy/Majorana/blob/main/GeneralizationMajorana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install iteration-utilities

Collecting iteration-utilities
  Downloading iteration_utilities-0.11.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: iteration-utilities
  Building wheel for iteration-utilities (setup.py) ... done
  Created wheel for iteration-utilities: filename=iteration_utilities-0.11.0-cp310-cp310-linux_x86_64.whl size=327854 sha256=e520e897b9136a20898a358d01d7d93a8dbde6db8789686407c54324402a0bd6
  Stored in directory: /root/.cache/pip/wheels/2d/ab/c4/309aa5942beba1f36d6744acf619b7a314fca50f6a7ccce68c
Successfully built iteration-utilities
Installing collected packages: iteration-utilities
Successfully installed iteration-utilities-0.11.0

In [2]:
import numpy as np
import pandas as pd
import json
from iteration_utilities import duplicates
import itertools

In [3]:
listan=pd.read_json("https://github.com/restrepo/anomaly/raw/main/solutions.json.gz")



### **Majorana**

Debemos tener en cuenta que necesitamos 3 valores iguales para $m$ y tres para el valor de los neutrinos $\nu$

\begin{equation}
\frac{2\nu}{\delta}= s
\end{equation}

solo se considera en está parte el caso en el que $\delta = 1$.

In [4]:
listan

,l,k,solution,gcd,n
0,"[-1, 0, -1, 0, -1]","[-1, 0, -1, 1, -1]","[1, 4, 4, 4, -5, -5, -5, -5, -5, 6, 6]",1,11
1,"[-1, 1]","[-1, 0, -1]","[1, 2, 2, -3, -3, -3, 4]",1,7
2,"[1, -1, 0, 1, -1]","[-2, 0, -1, -2, 0]","[1, 1, -2, -2, -3, -3, 5, 5, 5, 5, -6, -6]",2,12
3,"[-1, 1, -1, 1, -1]","[-2, -1, 0, -1, 0]","[1, 1, 1, 1, 2, 2, 2, -3, -4, -4, -6, 7]",1,12
4,"[1, 0, 1, 0, -1]","[-2, -1, -2, -1, 0]","[1, 1, 1, -2, -2, -5, -5, 6, 6, 7, -8]",1,11
...,...,...,...,...,...
390069,"[-3, -15, -6]","[-3, 8, 9]","[8, -9, -9, 11, 25, -29, -29, 32]",36,8
390070,"[-10, -5, -15]","[-10, -12, 12]","[5, 5, 5, -17, -27, -27, 28, 28]",100,8
390071,"[15, -1, 15]","[-14, -13, -14]","[14, -15, -16, 17, -30, 31, 31, -32]",1,8
390072,"[-15, -9, -1]","[-13, -14, -12]","[11, -13, -15, 19, 23, -26, -30, 31]",18,8
390073,"[10, 15, 5]","[-11, -14, 7]","[16, -17, -17, 19, 20, -22, -22, 23]",2000,8

In [5]:
listan_general = listan[listan['n']<=13].reset_index(drop=True)

In [6]:
listan_general

,l,k,solution,gcd,n
0,"[-1, 0, -1, 0, -1]","[-1, 0, -1, 1, -1]","[1, 4, 4, 4, -5, -5, -5, -5, -5, 6, 6]",1,11
1,"[-1, 1]","[-1, 0, -1]","[1, 2, 2, -3, -3, -3, 4]",1,7
2,"[1, -1, 0, 1, -1]","[-2, 0, -1, -2, 0]","[1, 1, -2, -2, -3, -3, 5, 5, 5, 5, -6, -6]",2,12
3,"[-1, 1, -1, 1, -1]","[-2, -1, 0, -1, 0]","[1, 1, 1, 1, 2, 2, 2, -3, -4, -4, -6, 7]",1,12
4,"[1, 0, 1, 0, -1]","[-2, -1, -2, -1, 0]","[1, 1, 1, -2, -2, -5, -5, 6, 6, 7, -8]",1,11
...,...,...,...,...,...
390069,"[-3, -15, -6]","[-3, 8, 9]","[8, -9, -9, 11, 25, -29, -29, 32]",36,8
390070,"[-10, -5, -15]","[-10, -12, 12]","[5, 5, 5, -17, -27, -27, 28, 28]",100,8
390071,"[15, -1, 15]","[-14, -13, -14]","[14, -15, -16, 17, -30, 31, 31, -32]",1,8
390072,"[-15, -9, -1]","[-13, -14, -12]","[11, -13, -15, 19, 23, -26, -30, 31]",18,8
390073,"[10, 15, 5]","[-11, -14, 7]","[16, -17, -17, 19, 20, -22, -22, 23]",2000,8

In [7]:
def listDups(listNums):
  return list(duplicates(listNums))

In [8]:
listan_general['repeated'] = listan_general['solution'].apply(listDups)

In [9]:

listan_general['repeated']

0         [4, 4, -5, -5, -5, -5, 6]
1                       [2, -3, -3]
2          [1, -2, -3, 5, 5, 5, -6]
3               [1, 1, 1, 2, 2, -4]
4                 [1, 1, -2, -5, 6]
                    ...
390069                    [-9, -29]
390070              [5, 5, -27, 28]
390071                         [31]
390072                           []
390073                   [-17, -22]
Name: repeated, Length: 390074, dtype: object

In [10]:
listan_General=listan_general[listan_general['repeated'].apply(len)>1].sort_values('n').reset_index(drop=True)

In [11]:
listan_General

,l,k,solution,gcd,n,repeated
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]"
1,"[0, -2]","[-1, -7, 9]","[1, 9, 9, -25, -25, 31]",8,6,"[9, -25]"
2,"[-3, 3]","[-3, -4]","[5, -9, -9, 16, 16, -19]",18,6,"[-9, 16]"
3,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]"
4,"[0, 1]","[-1, -4, 1]","[1, 1, 11, -16, -16, 19]",2,6,"[1, -16]"
...,...,...,...,...,...,...
137108,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]"
137109,"[1, -2, 2, -3, -2]","[-3, 0, -1, -2, 0]","[1, 1, 3, -5, 9, -10, -10, 15, 19, -27, -28, 32]",1,12,"[1, -10]"
137110,"[1, -2, -1, 3, -2]","[-3, 0, -1, -2, 0]","[2, 3, 7, -9, 10, -13, 14, 14, -15, -17, -17, 21]",4,12,"[14, -17]"
137111,"[1, -2, 3, 0, -2]","[-3, 0, -1, -2, 1]","[1, 2, 7, 7, -9, -9, 11, -12, -18, 21, 27, -28]",2,12,"[7, -9]"
137112,"[2, 0, -3, -1, 2]","[-3, -2, 1, 0, 1]","[1, -3, 6, -8, -9, 11, -16, -16, 18, 18, 24, -26]",2,12,"[-16, 18]"

In [12]:
listan_General['repeated'].apply(listDups).reset_index(drop=True)

0          [3]
1           []
2           []
3          [1]
4           []
          ...
137108    [-7]
137109      []
137110      []
137111      []
137112      []
Name: repeated, Length: 137113, dtype: object

In [13]:
solutions_interest=listan_General[listan_General['repeated'].apply(listDups).apply(len)==1].reset_index(drop=True)
solutions_interest

,l,k,solution,gcd,n,repeated
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]"
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]"
...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]"

In [14]:
solutions_interest['repeated'].apply(len)>1

0        True
1        True
2        True
3        True
4        True
         ...
31194    True
31195    True
31196    True
31197    True
31198    True
Name: repeated, Length: 31199, dtype: bool

In [15]:
solutions_interest[solutions_interest['repeated'].apply(len)>1] # Si no se resetea se toman los valores exactos de cada casilla.

,l,k,solution,gcd,n,repeated
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]"
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]"
...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]"

In [16]:
solutions_interest[solutions_interest['repeated'].apply(len)>1].reset_index(drop=True)

,l,k,solution,gcd,n,repeated
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]"
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]"
...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]"

In [34]:

#################################################################################
delta=1
def condition_model(l):
  d={} # Se inicializa un dicionario vacío
  ll=set(l)
  for n in ll:
    if l.count(n)>1: # Mayor que 1 porque si se repite más veces quiere decir que hay más 1 n.
      d['nu']=n # Entonces m=n
  if d.get('nu'): #.get--> forma segura de pedir un elemnto aunque no exista. Sí existe m volver a contar
    ll.remove(d['nu']) # removemos el elemento sí existe y ese el elemento que necesitamos como nu.
    #if len(ll)>0:
      #d['nu']=list(ll)[0] #nu es el número que se repite, por lo tanto se toma el primer elemento
    d['s']= 2*d['nu']/delta  # Ecuación del modelo.
    return d
  else:
    return {}

In [35]:
solutions_interest['condition_model']=solutions_interest['repeated'].apply(condition_model)

In [36]:
Solutions_Interest=solutions_interest[solutions_interest['condition_model'].apply(len)==2].reset_index(drop=True)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]","{'nu': 3, 's': 6.0}"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}"
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]","{'nu': -21, 's': -42.0}"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]","{'nu': -9, 's': -18.0}"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]","{'nu': -27, 's': -54.0}"
...,...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]","{'nu': -12, 's': -24.0}"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]","{'nu': 27, 's': 54.0}"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]","{'nu': 4, 's': 8.0}"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]","{'nu': 2, 's': 4.0}"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]","{'nu': -7, 's': -14.0}"

In [37]:

lista = Solutions_Interest
Solutions_Interest['solution_free'] =Solutions_Interest['solution']
lista
'''
for k in range(len(Solutions_Interest['solution'])):
  lista1 = Solutions_Interest['solution'][k]
  lista2 = Solutions_Interest['repeated'][k]
  l = []
  for i in lista1:
    for j in lista2:
      if i!=j:
        l.append(i)
        Solutions_Interest['solution_free'][k] = l
      else:
        continue
  '''

"\nfor k in range(len(Solutions_Interest['solution'])):\n  lista1 = Solutions_Interest['solution'][k]\n  lista2 = Solutions_Interest['repeated'][k]\n  l = []\n  for i in lista1:\n    for j in lista2:\n      if i!=j:\n        l.append(i)\n        Solutions_Interest['solution_free'][k] = l\n      else:\n        continue\n  "

In [38]:
for k in range(len(Solutions_Interest['solution'])):
  l = []
  lista1 = set(Solutions_Interest['solution'][k])
  lista2 = set(Solutions_Interest['repeated'][k])
  l.append(list(lista1-lista2))
  Solutions_Interest['solution_free'][k] = l[0]

<ipython-input-38-8a85160b1a19>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Solutions_Interest['solution_free'][k] = l[0]

In [39]:
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]","{'nu': 3, 's': 6.0}","[18, -10, -17]"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}",[5]
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]","{'nu': -21, 's': -42.0}","[24, 4, 12, 23]"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]","{'nu': -9, 's': -18.0}","[8, 1, 11, 7]"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]","{'nu': -27, 's': -54.0}","[32, 25, 2, 22]"
...,...,...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]","{'nu': -12, 's': -24.0}","[1, 3, 6, 10, 11, 13, -19, 20, -9]"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]","{'nu': 27, 's': 54.0}","[-25, 9, -6, -3, -2]"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]","{'nu': 4, 's': 8.0}","[3, -25, 12, -19, -18, 21, -7, 26, -5]"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]","{'nu': 2, 's': 4.0}","[3, -17, 15, -11, -10, -8, -4]"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]","{'nu': -7, 's': -14.0}","[3, 4, 13, 14, 15, 16, -17, -18, -9]"

In [40]:
Solutions_Interest1_=Solutions_Interest.apply(lambda row: row['condition_model'].get('s'), axis='columns' )
Solutions_Interest1_

0         6.0
1         2.0
2       -42.0
3       -18.0
4       -54.0
         ...
31194   -24.0
31195    54.0
31196     8.0
31197     4.0
31198   -14.0
Length: 31199, dtype: float64

In [41]:
Solutions_Interest['s'] = (Solutions_Interest1_)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]","{'nu': 3, 's': 6.0}","[18, -10, -17]",6.0
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}",[5],2.0
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]","{'nu': -21, 's': -42.0}","[24, 4, 12, 23]",-42.0
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]","{'nu': -9, 's': -18.0}","[8, 1, 11, 7]",-18.0
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]","{'nu': -27, 's': -54.0}","[32, 25, 2, 22]",-54.0
...,...,...,...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]","{'nu': -12, 's': -24.0}","[1, 3, 6, 10, 11, 13, -19, 20, -9]",-24.0
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]","{'nu': 27, 's': 54.0}","[-25, 9, -6, -3, -2]",54.0
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]","{'nu': 4, 's': 8.0}","[3, -25, 12, -19, -18, 21, -7, 26, -5]",8.0
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]","{'nu': 2, 's': 4.0}","[3, -17, 15, -11, -10, -8, -4]",4.0
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]","{'nu': -7, 's': -14.0}","[3, 4, 13, 14, 15, 16, -17, -18, -9]",-14.0

In [42]:
def Massless(x,s):
  if True:
    xx=x.copy()
    d= []
    if len(x)>0:
      for x in itertools.permutations(x,2):
        if x[0]<=x[1]:
          d.append(x)
    for j in d:
      if abs(sum(j))== abs(s):
        d.remove(j)
        j=list(j)
        for elements in j:
          if elements in xx:
            xx.remove(elements)

  return xx

In [43]:
Solutions_Interest['Massless']=Solutions_Interest.apply(lambda row: Massless(row['solution_free'], row['s']),axis="columns" )
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[-3, -1]","[-3, -4]","[3, 3, 3, -10, -17, 18]",2,6,"[3, 3]","{'nu': 3, 's': 6.0}","[18, -10, -17]",6.0,"[18, -10, -17]"
1,"[-1, -2]","[-1, 2]","[1, 1, 1, -4, -4, 5]",1,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}",[5],2.0,[5]
2,"[-4, -6]","[-9, -10, -7]","[4, 12, -21, -21, -21, 23, 24]",21,7,"[-21, -21]","{'nu': -21, 's': -42.0}","[24, 4, 12, 23]",-42.0,"[24, 4, 12, 23]"
3,"[-1, 0, -2]","[-1, 0, -1]","[1, 7, 8, -9, -9, -9, 11]",1,7,"[-9, -9]","{'nu': -9, 's': -18.0}","[8, 1, 11, 7]",-18.0,"[8, 1]"
4,"[-1, 1]","[-1, 0, -5]","[2, 22, 25, -27, -27, -27, 32]",1,7,"[-27, -27]","{'nu': -27, 's': -54.0}","[32, 25, 2, 22]",-54.0,"[25, 2]"
...,...,...,...,...,...,...,...,...,...,...
31194,"[-1, -2, -3, 2, -2]","[-3, 0, -1, -2, 0]","[1, 3, 6, -9, 10, 11, -12, -12, -12, 13, -19, 20]",2,12,"[-12, -12]","{'nu': -12, 's': -24.0}","[1, 3, 6, 10, 11, 13, -19, 20, -9]",-24.0,"[1, 3, 6, 10, -19, 20, -9]"
31195,"[1, -3, 0, 3, -3]","[-3, 0, -1, -2, 0]","[1, 1, -2, -3, -6, 9, -25, 27, 27, 27, -28, -28]",3,12,"[1, 27, 27, -28]","{'nu': 27, 's': 54.0}","[-25, 9, -6, -3, -2]",54.0,"[-25, 9, -6, -3, -2]"
31196,"[1, -3, 3, 1, -1]","[-3, 0, -1, -2, 0]","[3, 4, 4, 4, -5, -7, 12, -18, -19, 21, -25, 26]",2,12,"[4, 4]","{'nu': 4, 's': 8.0}","[3, -25, 12, -19, -18, 21, -7, 26, -5]",8.0,"[3, -25, 12, -19, 21, -7, -5]"
31197,"[-1, 2, -1, -2, -3]","[-2, -3, -2, 2, 0]","[2, 2, 2, 3, -4, -8, -10, -11, 13, 13, 15, -17]",2,12,"[2, 2, 13]","{'nu': 2, 's': 4.0}","[3, -17, 15, -11, -10, -8, -4]",4.0,"[3, -17, -10, -8, -4]"
31198,"[1, -1, -3, 1, 2]","[-3, 0, -1, -2, 0]","[3, 4, -7, -7, -7, -9, 13, 14, 15, 16, -17, -18]",3,12,"[-7, -7]","{'nu': -7, 's': -14.0}","[3, 4, 13, 14, 15, 16, -17, -18, -9]",-14.0,"[13, 14, 15, 16, -9]"

In [44]:
Solution_Mass = Solutions_Interest[Solutions_Interest['Massless'].apply(lambda l: l==[] if isinstance(l,list) else False)].reset_index(drop=True)
Solution_Mass

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[-2, -1, 0]","[-1, -4, -5, -4]","[1, -5, 8, 8, 8, -11, -12, -12, 15]",2,9,"[8, 8, -12]","{'nu': 8, 's': 16.0}","[1, -5, -11, 15]",16.0,[]
1,"[-2, 0, 1]","[-1, -8, -7, 8]","[3, -13, 16, 16, 16, -19, -24, -24, 29]",4,9,"[16, 16, -24]","{'nu': 16, 's': 32.0}","[29, 3, -19, -13]",32.0,[]
2,"[3, -3, -1, 1]","[-1, -3, 0, -2, 0]","[1, 1, 1, 3, 3, -9, 11, -13, -15, 17]",4,10,"[1, 1, 3]","{'nu': 1, 's': 2.0}","[11, -15, 17, -13, -9]",2.0,[]
3,"[-3, -1, -2, -3]","[-1, -4, 0, -1, 2]","[2, 2, -5, -5, 8, 8, -12, -12, -12, 13, 13]",2,11,"[2, -5, 8, -12, -12, 13]","{'nu': -12, 's': -24.0}",[],-24.0,[]
4,"[-4, 2, -1, 0]","[-1, -2, 2, -2, 2]","[4, 4, -10, -10, 11, 11, -12, -12, -12, 13, 13]",2,11,"[4, -10, 11, -12, -12, 13]","{'nu': -12, 's': -24.0}",[],-24.0,[]
5,"[-2, 1, -3, -2]","[-4, -3, 0, -4, -3]","[5, -8, -8, -8, -9, 12, 20, 20, -21, 25, -28]",4,11,"[-8, -8, 20]","{'nu': -8, 's': -16.0}","[-28, 5, -21, 12, -9, 25]",-16.0,[]
6,"[-3, 1, 2, 0]","[-1, -3, -2, -4, 4]","[1, -2, -2, 4, 4, 4, 7, -8, -9, -15, 16]",1,11,"[-2, 4, 4]","{'nu': 4, 's': 8.0}","[1, 7, 16, -15, -9, -8]",8.0,[]
7,"[4, 1, 4, 1]","[-2, -4, -2, -4, 3]","[4, 9, 9, -12, -12, -12, 14, 14, -17, -17, 20]",6,11,"[9, -12, -12, 14, -17]","{'nu': -12, 's': -24.0}","[4, 20]",-24.0,[]
8,"[3, -4, 2, 1]","[-2, -4, -2, -4, 1]","[4, 4, 4, -9, -10, -10, -11, 14, 17, 19, -22]",6,11,"[4, 4, -10]","{'nu': 4, 's': 8.0}","[-22, 14, 17, 19, -11, -9]",8.0,[]
9,"[-3, 4, 1, -3]","[-2, -4, -1, 2, 1]","[1, 1, 2, 2, 4, 4, 4, -9, -13, -13, 17]",6,11,"[1, 2, 4, 4, -13]","{'nu': 4, 's': 8.0}","[17, -9]",8.0,[]
10,"[-2, -4, 0, -1]","[-2, -1, -3, 0, -2]","[3, 4, 4, 4, 5, 6, -9, -10, -10, -14, 17]",1,11,"[4, 4, -10]","{'nu': 4, 's': 8.0}","[3, 5, 6, 17, -14, -9]",8.0,[]
11,"[3, 2, 1, 4]","[-4, 3, -1, 0, -1]","[1, 1, 2, 2, -9, -9, -10, 12, 12, 12, -14]",6,11,"[1, 2, -9, 12, 12]","{'nu': 12, 's': 24.0}","[-14, -10]",24.0,[]
12,"[-4, 3, -2, 0]","[-1, -3, 4, -4, 4]","[1, -3, -4, -4, -4, 7, 10, 10, 11, -12, -12]",2,11,"[-4, -4, 10, -12]","{'nu': -4, 's': -8.0}","[1, 11, -3, 7]",-8.0,[]
13,"[-2, -4, -1, -3]","[-2, -3, -4, 0, -2]","[3, -4, -4, -4, -6, 7, 10, 10, -11, 14, -15]",1,11,"[-4, -4, 10]","{'nu': -4, 's': -8.0}","[3, 7, 14, -15, -11, -6]",-8.0,[]
14,"[-1, -4, 0, 1]","[-4, -2, -3, 1, -2]","[3, 7, 8, 8, 8, 9, -12, -19, -20, -20, 28]",4,11,"[8, 8, -20]","{'nu': 8, 's': 16.0}","[3, 7, 9, -19, -12, 28]",16.0,[]
15,"[-2, 1, -2, 0]","[-4, 0, -4, -3, 1]","[3, -4, -8, -8, -8, 9, -12, 13, 20, 20, -25]",12,11,"[-8, -8, 20]","{'nu': -8, 's': -16.0}","[3, -25, 9, 13, -12, -4]",-16.0,[]
16,"[1, 2, -1, 1]","[-3, -2, 0, 2, 3]","[2, 4, 4, 4, 6, -9, -13, 17, -18, -18, 21]",2,11,"[4, 4, -18]","{'nu': 4, 's': 8.0}","[2, 6, 17, -13, 21, -9]",8.0,[]
17,"[-2, 0, -3, 1, 2]","[-2, -1, 0, -2, -1]","[1, -2, -2, -4, -4, -4, 5, 5, 7, 7, -9]",1,11,"[-2, -4, -4, 5, 7]","{'nu': -4, 's': -8.0}","[1, -9]",-8.0,[]
18,"[-3, -1, -2, -3, -1]","[-2, -1, 2, 0, -1]","[1, 2, 3, -4, -4, -4, 6, -9, 10, 10, -11]",1,11,"[-4, -4, 10]","{'nu': -4, 's': -8.0}","[1, 2, 3, 6, -11, -9]",-8.0,[]
19,"[3, 0, -2, 1, -2]","[-1, 1, -1, -2, 0]","[1, 1, 1, -3, 5, -7, -14, -15, 16, 17, 20, -22]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, -22, 16, -15, -14, 17, 20, -7, -3]",2.0,[]
20,"[1, -1, -2, 1, 2]","[-3, 0, -3, -1, 0]","[1, 1, 1, -2, -3, 4, 5, -7, 14, -15, -16, 17]",1,12,"[1, 1]","{'nu': 1, 's': 2.0}","[4, 5, 14, -16, -15, 17, -7, -3, -2]",2.0,[]
21,"[-1, -2, -1, 1, -1]","[-2, -3, -2, 0, -2]","[1, 2, 2, 2, 3, 6, 7, -8, -8, -10, -11, 14]",2,12,"[2, 2, -8]","{'nu': 2, 's': 4.0}","[1, 3, 6, 7, 14, -11, -10]",4.0,[]
22,"[-3, 3, -3, -2, -1]","[-2, -1, 0, 1, -2]","[1, 1, 1, -6, -6, 10, 11, -12, -13, 14, 15, -16]",4,12,"[1, 1, -6]","{'nu': 1, 's': 2.0}","[10, 11, 14, 15, -16, -13, -12]",2.0,[]
23,"[1, -2, -1, -2, -3]","[-2, -1, -3, -1, 2]","[1, 1, 1, -3, 5, -7, -10, -11, 12, 13, 14, -16]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, 12, 13, 14, -16, -11, -10, -7, -3]",2.0,[]

In [49]:
Solution_MassFinal=Solution_Mass[Solution_Mass['repeated'].apply(len)==2].reset_index(drop=True)
Solution_MassFinal

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless,nmax
0,"[1, -2, -1, -2, -3]","[-2, -1, -3, -1, 2]","[1, 1, 1, -3, 5, -7, -10, -11, 12, 13, 14, -16]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, 12, 13, 14, -16, -11, -10, -7, -3]",2.0,[],16
1,"[1, -1, -2, 1, 2]","[-3, 0, -3, -1, 0]","[1, 1, 1, -2, -3, 4, 5, -7, 14, -15, -16, 17]",1,12,"[1, 1]","{'nu': 1, 's': 2.0}","[4, 5, 14, -16, -15, 17, -7, -3, -2]",2.0,[],17
2,"[3, 0, -2, 1, -2]","[-1, 1, -1, -2, 0]","[1, 1, 1, -3, 5, -7, -14, -15, 16, 17, 20, -22]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, -22, 16, -15, -14, 17, 20, -7, -3]",2.0,[],22