<a href="https://colab.research.google.com/github/AgudeloKimy/Majorana/blob/main/Majoranadelta1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install iteration-utilities

Collecting iteration-utilities
  Downloading iteration_utilities-0.11.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: iteration-utilities
  Building wheel for iteration-utilities (setup.py) ... done
  Created wheel for iteration-utilities: filename=iteration_utilities-0.11.0-cp310-cp310-linux_x86_64.whl size=327848 sha256=86f31de3c60745501a5058acd89e93744dc87abb04a39fa381a0d609921b49fa
  Stored in directory: /root/.cache/pip/wheels/2d/ab/c4/309aa5942beba1f36d6744acf619b7a314fca50f6a7ccce68c
Successfully built iteration-utilities
Installing collected packages: iteration-utilities
Successfully installed iteration-utilities-0.11.0

In [2]:
import numpy as np
import pandas as pd
import json
from iteration_utilities import duplicates
import itertools

In [3]:
df  = pd.read_json('solutions.json')

### **Majorana**

Debemos tener en cuenta que necesitamos 3 valores iguales para $m$ y tres para el valor de los neutrinos $\nu$

\begin{equation}
\frac{2\nu}{\delta}= s
\end{equation}

solo se considera en está parte el caso en el que $\delta = 1$.

\begin{equation}
2{\nu}= s
\end{equation}

In [4]:
listan_general = df[df['n']<=13].reset_index(drop=True)

In [5]:
def listDups(listNums):
  return list(duplicates(listNums))

In [6]:
listan_general['repeated'] = listan_general['solution'].apply(listDups)

In [7]:
listan_General=listan_general[listan_general['repeated'].apply(len)>1].sort_values('n').reset_index(drop=True)
listan_General

,l,k,solution,gcd,n,repeated
0,"[1, -1]","[1, 5]","[1, 1, 19, -25, -25, 29]",2,6,"[1, -25]"
1,"[-1, 1]","[-1, -4]","[1, 1, 11, -16, -16, 19]",2,6,"[1, -16]"
2,"[4, -4]","[4, 3]","[5, -9, -9, 16, 16, -19]",32,6,"[-9, 16]"
3,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
4,"[-4, 4]","[-4, -5]","[11, -16, -16, 25, 25, -29]",32,6,"[-16, 25]"
...,...,...,...,...,...,...
1211702,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"
1211703,"[-4, -9, 0, -8, -5]","[-7, 5, 4, 2, -3]","[2, -4, -4, -7, -7, -11, 18, 19, 22, 22, -23, ...",34,12,"[-4, -7, 22]"
1211704,"[7, -9, 2, 6, 7]","[-8, 9, 2, 6, 4]","[7, -8, -8, 12, -13, 14, 18, 22, -24, -25, -25...",329,12,"[-8, -25]"
1211705,"[-9, 0, -3, 0, 6]","[-2, 2, -2, 2, 7]","[2, -6, -6, -6, -6, -6, 10, -13, 18, 19, 21, -27]",144,12,"[-6, -6, -6, -6]"
1211706,"[-10, -20, 9, 7, 16]","[-5, 3, -4, -8, 8]","[1, 1, -5, -5, -7, -10, 15, 15, 17, -24, -24, 26]",1028,12,"[1, -5, 15, -24]"

In [8]:
listan_General['repeated'].apply(listDups).reset_index(drop=True)

0                    []
1                    []
2                    []
3                   [1]
4                    []
               ...
1211702            [27]
1211703              []
1211704              []
1211705    [-6, -6, -6]
1211706              []
Name: repeated, Length: 1211707, dtype: object

In [9]:
solutions_interest=listan_General[listan_General['repeated'].apply(listDups).apply(len)==1].reset_index(drop=True)
solutions_interest

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [10]:
solutions_interest[solutions_interest['repeated'].apply(len)>1] # Si no se resetea se toman los valores exactos de cada casilla.

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [11]:
solutions_interest[solutions_interest['repeated'].apply(len)>1].reset_index(drop=True)

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [12]:
#################################################################################
delta=1
def condition_model(l):
  d={} # Se inicializa un dicionario vacío
  ll=set(l)
  for n in ll:
    if l.count(n)>1: # Mayor que 1 porque si se repite más veces quiere decir que hay más 1 n.
      d['nu']=n # Entonces m=n
  if d.get('nu'): #.get--> forma segura de pedir un elemnto aunque no exista. Sí existe m volver a contar
    ll.remove(d['nu']) # removemos el elemento sí existe y ese el elemento que necesitamos como nu.
    #if len(ll)>0:
      #d['nu']=list(ll)[0] #nu es el número que se repite, por lo tanto se toma el primer elemento
    d['s']= 2*d['nu']/delta  # Ecuación del modelo.
    return d
  else:
    return {}

In [13]:
solutions_interest['condition_model']=solutions_interest['repeated'].apply(condition_model)
Solutions_Interest=solutions_interest[solutions_interest['condition_model'].apply(len)==2].reset_index(drop=True)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]","{'nu': 3, 's': 6.0}"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]","{'nu': 3, 's': 6.0}"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]","{'nu': -11, 's': -22.0}"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]","{'nu': -19, 's': -38.0}"
...,...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]","{'nu': -3, 's': -6.0}"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]","{'nu': 9, 's': 18.0}"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]","{'nu': -24, 's': -48.0}"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]","{'nu': -5, 's': -10.0}"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]","{'nu': 27, 's': 54.0}"

In [14]:

lista = Solutions_Interest
Solutions_Interest['solution_free'] =Solutions_Interest['solution']
lista
'''
for k in range(len(Solutions_Interest['solution'])):
  lista1 = Solutions_Interest['solution'][k]
  lista2 = Solutions_Interest['repeated'][k]
  l = []
  for i in lista1:
    for j in lista2:
      if i!=j:
        l.append(i)
        Solutions_Interest['solution_free'][k] = l
      else:
        continue
  '''

"\nfor k in range(len(Solutions_Interest['solution'])):\n  lista1 = Solutions_Interest['solution'][k]\n  lista2 = Solutions_Interest['repeated'][k]\n  l = []\n  for i in lista1:\n    for j in lista2:\n      if i!=j:\n        l.append(i)\n        Solutions_Interest['solution_free'][k] = l\n      else:\n        continue\n  "

In [15]:
for k in range(len(Solutions_Interest['solution'])):
  l = []
  lista1 = set(Solutions_Interest['solution'][k])
  lista2 = set(Solutions_Interest['repeated'][k])
  l.append(list(lista1-lista2))
  Solutions_Interest['solution_free'][k] = l[0]

<ipython-input-15-8a85160b1a19>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Solutions_Interest['solution_free'][k] = l[0]

In [16]:
Solutions_Interest1_=Solutions_Interest.apply(lambda row: row['condition_model'].get('s'), axis='columns' )
Solutions_Interest['s'] = (Solutions_Interest1_)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]","{'nu': 1, 's': 2.0}",[5],2.0
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]","{'nu': 3, 's': 6.0}","[18, -10, -17]",6.0
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]","{'nu': 3, 's': 6.0}","[8, -7]",6.0
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]","{'nu': -11, 's': -22.0}","[8, 9, 2, 14]",-22.0
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]","{'nu': -19, 's': -38.0}","[16, 1, 18, 22]",-38.0
...,...,...,...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]","{'nu': -3, 's': -6.0}","[-26, -25, 7, 17, 18, -13, 29]",-6.0
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]","{'nu': 9, 's': 18.0}","[3, -24, -20, 12, 13, -8, 29]",18.0
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]","{'nu': -24, 's': -48.0}","[19, 12, 13]",-48.0
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]","{'nu': -5, 's': -10.0}","[2, -27, -23, -18, 15, 21, 29]",-10.0
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]","{'nu': 27, 's': 54.0}","[-30, -26, -25, 14, -10]",54.0

In [17]:
def Massless(x,s):
  if True:
    xx=x.copy()
    d= []
    if len(x)>0:
      for x in itertools.permutations(x,2):
        if x[0]<=x[1]:
          d.append(x)
    for j in d:
      if abs(sum(j))== abs(s):
        d.remove(j)
        j=list(j)
        for elements in j:
          if elements in xx:
            xx.remove(elements)

  return xx

In [18]:
Solutions_Interest['Massless']=Solutions_Interest.apply(lambda row: Massless(row['solution_free'], row['s']),axis="columns" )

In [19]:
Solution_Mass = Solutions_Interest[Solutions_Interest['Massless'].apply(lambda l: l==[] if isinstance(l,list) else False)].reset_index(drop=True)
Solution_Mass

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[-8, -7, 8]","[1, -1, 0, 2]","[3, -13, 16, 16, 16, -19, -24, -24, 29]",4,9,"[16, 16, -24]","{'nu': 16, 's': 32.0}","[29, 3, -19, -13]",32.0,[]
1,"[4, 3, 0]","[1, 2, -2, -3]","[1, -5, 8, 8, 8, -11, -12, -12, 15]",6,9,"[8, 8, -12]","{'nu': 8, 's': 16.0}","[1, -5, -11, 15]",16.0,[]
2,"[-1, -3, 0, -2]","[-3, 3, 1, -1]","[1, 1, 1, 3, 3, -9, 11, -13, -15, 17]",4,10,"[1, 1, 3]","{'nu': 1, 's': 2.0}","[11, -15, 17, -13, -9]",2.0,[]
3,"[-6, 2, 3, 4]","[1, 5, -4, -3, -2]","[1, -4, -4, -4, 7, -9, 17, 18, 18, -20, -20]",6,11,"[-4, -4, 18, -20]","{'nu': -4, 's': -8.0}","[1, -9, 17, 7]",-8.0,[]
4,"[3, -1, 3, -3]","[2, 6, -1, 0, 5]","[5, 7, 8, -12, -12, -12, 16, 17, -18, -18, 19]",12,11,"[-12, -12, -18]","{'nu': -12, 's': -24.0}","[5, 7, 8, 16, 17, 19]",-24.0,[]
...,...,...,...,...,...,...,...,...,...,...
71,"[6, 2, -2, -5, -1]","[5, 0, -4, 9, 1]","[2, 2, 2, -6, 10, -14, -15, -18, 19, 21, 22, -25]",117,12,"[2, 2]","{'nu': 2, 's': 4.0}","[-25, 10, -18, -15, -14, 19, 21, 22, -6]",4.0,[]
72,"[1, 0, 7, 8, 7]","[10, -8, 5, 3, 5]","[1, 1, 1, -3, 5, -7, -15, 17, -24, 26, 28, -30]",94,12,"[1, 1]","{'nu': 1, 's': 2.0}","[-30, 5, -24, -15, 17, -7, 26, 28, -3]",2.0,[]
73,"[1, 0, 5, 4, 1]","[-9, -10, -2, -6, -2]","[1, 2, 2, 2, 3, -6, 10, -14, 23, -26, -27, 30]",12,12,"[2, 2]","{'nu': 2, 's': 4.0}","[1, 3, -27, -26, 10, -14, 23, -6, 30]",4.0,[]
74,"[-8, -10, -2, 1, 4]","[-10, -8, -10, -8, 0]","[4, 4, 4, -7, 12, 15, -16, -16, 17, -20, -25, 28]",48,12,"[4, 4, -16]","{'nu': 4, 's': 8.0}","[-25, 12, -20, 15, 17, -7, 28]",8.0,[]
75,"[2, -8, -9, 3, 9]","[2, 6, 2, 0, -8]","[1, -3, -3, -3, -7, -9, -11, 12, 12, 15, 17, -21]",8,12,"[-3, -3, 12]","{'nu': -3, 's': -6.0}","[1, -21, 15, 17, -11, -9, -7]",-6.0,[]

In [20]:
Solution_MassFinal=Solution_Mass[Solution_Mass['repeated'].apply(len)==2].reset_index(drop=True)
Solution_MassFinal

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[1, -4, 9, -4]","[-2, 4, 10, -9, 1]","[1, -3, -3, -3, 5, -7, 10, -16, 17, 22, -23]",316,11,"[-3, -3]","{'nu': -3, 's': -6.0}","[1, 5, -23, 10, -16, 17, 22, -7]",-6.0,[]
1,"[-1, 8, -10, 8, 1]","[-5, -3, -6, 4, -5]","[1, 1, 1, -3, 5, -7, -12, 14, -19, 21, 22, -24]",240,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, -24, -19, 14, -12, 21, 22, -7, -3]",2.0,[]
2,"[-6, -8, 3, -8, -6]","[-4, -10, -4, 0, -6]","[3, 3, 3, -6, 8, -9, 12, -14, 15, -17, -21, 23]",168,12,"[3, 3]","{'nu': 3, 's': 6.0}","[8, -21, 12, 15, -17, -14, 23, -9, -6]",6.0,[]
3,"[6, -7, 6, -8, -2]","[-2, -7, 9, 10, 6]","[2, 2, 2, -3, -6, 7, 10, -14, 19, -22, -23, 26]",336,12,"[2, 2]","{'nu': 2, 's': 4.0}","[26, 7, -23, 10, -22, -14, 19, -6, -3]",4.0,[]
4,"[-6, -4, -6, 6, 2]","[2, -3, 7, -10, -6]","[2, 2, 2, -5, -6, 9, 10, -14, 15, -18, -19, 22]",440,12,"[2, 2]","{'nu': 2, 's': 4.0}","[9, 10, -19, -18, 15, -14, 22, -6, -5]",4.0,[]
5,"[-2, -6, 9, -6, -2]","[6, -6, -5, 3, -10]","[2, 2, 2, -6, -9, 10, 13, -14, 17, -18, -21, 22]",216,12,"[2, 2]","{'nu': 2, 's': 4.0}","[10, -21, 13, -18, 17, -14, 22, -9, -6]",4.0,[]
6,"[-5, 6, 0, 1, 7]","[7, 9, 10, -1, 6]","[1, 1, 1, -3, 5, -7, -8, 10, -19, 20, 21, -22]",44,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, 10, -22, -19, 20, 21, -8, -7, -3]",2.0,[]
7,"[-3, 0, -2, -1, -2]","[1, -1, 1, 2, 0]","[1, 1, 1, -3, 5, -7, -10, -11, 12, 13, 14, -16]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, 12, 13, 14, -16, -11, -10, -7, -3]",2.0,[]
8,"[1, 0, -2, 1, 3]","[1, -1, -2, -3, -2]","[1, 1, 1, -2, -3, 4, 5, -7, 14, -15, -16, 17]",4,12,"[1, 1]","{'nu': 1, 's': 2.0}","[4, 5, 14, -16, -15, 17, -7, -3, -2]",2.0,[]
9,"[-1, -7, 4, 0, 8]","[-5, 5, -5, 6, -1]","[4, 4, 4, -12, 13, -16, -19, 20, -21, 24, 27, ...",44,12,"[4, 4]","{'nu': 4, 's': 8.0}","[-28, -21, -19, 13, -16, -12, 20, 24, 27]",8.0,[]
10,"[-5, 5, -8, 0, -8]","[4, 2, 4, 1, -1]","[3, 4, 4, 4, -11, -12, -13, -16, 20, 21, 24, -28]",48,12,"[4, 4]","{'nu': 4, 's': 8.0}","[3, -28, -16, -13, -12, -11, 20, 21, 24]",8.0,[]
11,"[-7, 4, 1, 8, 2]","[1, -4, -2, 4, 9]","[1, 1, 1, -3, 5, -7, -14, -15, 16, 17, 20, -22]",105,12,"[1, 1]","{'nu': 1, 's': 2.0}","[5, -22, 16, -15, -14, 17, 20, -7, -3]",2.0,[]
12,"[-9, 2, 3, -3, 3]","[6, 3, 6, 3, -8]","[3, 3, 3, 8, -9, -12, -13, -14, 15, 18, 19, -21]",102,12,"[3, 3]","{'nu': 3, 's': 6.0}","[8, -21, 15, -14, -13, -12, 18, 19, -9]",6.0,[]
13,"[6, 2, -2, -5, -1]","[5, 0, -4, 9, 1]","[2, 2, 2, -6, 10, -14, -15, -18, 19, 21, 22, -25]",117,12,"[2, 2]","{'nu': 2, 's': 4.0}","[-25, 10, -18, -15, -14, 19, 21, 22, -6]",4.0,[]
14,"[1, 0, 7, 8, 7]","[10, -8, 5, 3, 5]","[1, 1, 1, -3, 5, -7, -15, 17, -24, 26, 28, -30]",94,12,"[1, 1]","{'nu': 1, 's': 2.0}","[-30, 5, -24, -15, 17, -7, 26, 28, -3]",2.0,[]
15,"[1, 0, 5, 4, 1]","[-9, -10, -2, -6, -2]","[1, 2, 2, 2, 3, -6, 10, -14, 23, -26, -27, 30]",12,12,"[2, 2]","{'nu': 2, 's': 4.0}","[1, 3, -27, -26, 10, -14, 23, -6, 30]",4.0,[]