<a href="https://colab.research.google.com/github/AgudeloKimy/Majorana/blob/main/Majoranadelta2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install iteration-utilities

Collecting iteration-utilities
  Downloading iteration_utilities-0.11.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: iteration-utilities
  Building wheel for iteration-utilities (setup.py) ... done
  Created wheel for iteration-utilities: filename=iteration_utilities-0.11.0-cp310-cp310-linux_x86_64.whl size=327854 sha256=26e6edc3e1e6ad48d69a8771698c30881a5d6d2603f08407221112c06b248552
  Stored in directory: /root/.cache/pip/wheels/2d/ab/c4/309aa5942beba1f36d6744acf619b7a314fca50f6a7ccce68c
Successfully built iteration-utilities
Installing collected packages: iteration-utilities
Successfully installed iteration-utilities-0.11.0

In [2]:
import numpy as np
import pandas as pd
import json
from iteration_utilities import duplicates
import itertools

In [5]:
df  = pd.read_json('solutions.json')

### **Majorana**

Debemos tener en cuenta que necesitamos 3 valores iguales para $m$ y tres para el valor de los neutrinos $\nu$

\begin{equation}
\frac{2\nu}{\delta}= s
\end{equation}

solo se considera en está parte el caso en el que $\delta = 2$.

\begin{equation}
{\nu}= s
\end{equation}

In [6]:
df

,l,k,solution,gcd,n
0,"[-1, 1, -1, 1]","[-1, 0, -1, 0]","[1, 1, 1, 1, 1, -2, -2, -2, -2, 3]",2,10
1,"[1, -1, 1, -1]","[1, 0, 1, 0, 1]","[1, 4, 4, 4, -5, -5, -5, -5, -5, 6, 6]",1,11
2,"[1, 0]","[-1, 1, -1]","[1, 2, 2, -3, -3, -3, 4]",1,7
3,"[-1, 1, 0, -2, -1]","[2, 1, -2, -1, 2]","[1, -4, -7, -7, 10, 10, 14, 14, -17, -17, -17,...",1,12
4,"[-1, 0, -2, 2, -2]","[-1, -2, 2, -1, 0]","[2, 2, 3, -4, 5, 5, -7, -7, 9, -10, -10, 12]",1,12
...,...,...,...,...,...
2296610,"[17, 7, 15, 11, 9]","[3, -10, -20, -3, 16]","[3, 3, 5, 7, -8, -8, 12, -13, 17, -20, -25, 27]",796,12
2296611,"[-9, -7, -8, 10, 19]","[-13, -20, -6, 20, -13]","[3, 6, 9, -12, 13, 13, -14, -22, -27, -28, 29,...",6425,12
2296612,"[-20, -3, 10, -13, -16]","[19, 0, -5, -6, -3]","[1, 3, 4, 4, -5, -8, -16, 19, 19, 19, -20, -20]",1350,12
2296613,"[20, 6, 20, 6, 10]","[-19, 10, -18, -11, 14]","[1, -8, -8, -9, 13, 15, 15, -17, 19, 19, -20, ...",10892,12
2296614,"[-10, -20, 9, 7, 16]","[-5, 3, -4, -8, 8]","[1, 1, -5, -5, -7, -10, 15, 15, 17, -24, -24, 26]",1028,12

In [7]:
listan_general = df[df['n']<=13].reset_index(drop=True)

In [8]:
def listDups(listNums):
  return list(duplicates(listNums))

In [9]:
listan_general['repeated'] = listan_general['solution'].apply(listDups)

In [10]:
listan_General=listan_general[listan_general['repeated'].apply(len)>1].sort_values('n').reset_index(drop=True)
listan_General

,l,k,solution,gcd,n,repeated
0,"[1, -1]","[1, 5]","[1, 1, 19, -25, -25, 29]",2,6,"[1, -25]"
1,"[-1, 1]","[-1, -4]","[1, 1, 11, -16, -16, 19]",2,6,"[1, -16]"
2,"[4, -4]","[4, 3]","[5, -9, -9, 16, 16, -19]",32,6,"[-9, 16]"
3,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
4,"[-4, 4]","[-4, -5]","[11, -16, -16, 25, 25, -29]",32,6,"[-16, 25]"
...,...,...,...,...,...,...
1211702,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"
1211703,"[-4, -9, 0, -8, -5]","[-7, 5, 4, 2, -3]","[2, -4, -4, -7, -7, -11, 18, 19, 22, 22, -23, ...",34,12,"[-4, -7, 22]"
1211704,"[7, -9, 2, 6, 7]","[-8, 9, 2, 6, 4]","[7, -8, -8, 12, -13, 14, 18, 22, -24, -25, -25...",329,12,"[-8, -25]"
1211705,"[-9, 0, -3, 0, 6]","[-2, 2, -2, 2, 7]","[2, -6, -6, -6, -6, -6, 10, -13, 18, 19, 21, -27]",144,12,"[-6, -6, -6, -6]"
1211706,"[-10, -20, 9, 7, 16]","[-5, 3, -4, -8, 8]","[1, 1, -5, -5, -7, -10, 15, 15, 17, -24, -24, 26]",1028,12,"[1, -5, 15, -24]"

In [11]:
listan_General['repeated'].apply(listDups).reset_index(drop=True)

0                    []
1                    []
2                    []
3                   [1]
4                    []
               ...
1211702            [27]
1211703              []
1211704              []
1211705    [-6, -6, -6]
1211706              []
Name: repeated, Length: 1211707, dtype: object

In [12]:
solutions_interest=listan_General[listan_General['repeated'].apply(listDups).apply(len)==1].reset_index(drop=True)
solutions_interest

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [14]:
solutions_interest[solutions_interest['repeated'].apply(len)>1] # Si no se resetea se toman los valores exactos de cada casilla.

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [15]:
solutions_interest[solutions_interest['repeated'].apply(len)>1].reset_index(drop=True)

,l,k,solution,gcd,n,repeated
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]"
...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]"

In [16]:
#################################################################################
delta=2
def condition_model(l):
  d={} # Se inicializa un dicionario vacío
  ll=set(l)
  for n in ll:
    if l.count(n)>1: # Mayor que 1 porque si se repite más veces quiere decir que hay más 1 n.
      d['nu']=n # Entonces m=n
  if d.get('nu'): #.get--> forma segura de pedir un elemnto aunque no exista. Sí existe m volver a contar
    ll.remove(d['nu']) # removemos el elemento sí existe y ese el elemento que necesitamos como nu.
    #if len(ll)>0:
      #d['nu']=list(ll)[0] #nu es el número que se repite, por lo tanto se toma el primer elemento
    d['s']= 2*d['nu']/delta  # Ecuación del modelo.
    return d
  else:
    return {}

In [17]:
solutions_interest['condition_model']=solutions_interest['repeated'].apply(condition_model)

In [18]:
Solutions_Interest=solutions_interest[solutions_interest['condition_model'].apply(len)==2].reset_index(drop=True)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]","{'nu': 1, 's': 1.0}"
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]","{'nu': 3, 's': 3.0}"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]","{'nu': 3, 's': 3.0}"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]","{'nu': -11, 's': -11.0}"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]","{'nu': -19, 's': -19.0}"
...,...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]","{'nu': -3, 's': -3.0}"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]","{'nu': 9, 's': 9.0}"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]","{'nu': -24, 's': -24.0}"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]","{'nu': -5, 's': -5.0}"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]","{'nu': 27, 's': 27.0}"

In [19]:

lista = Solutions_Interest
Solutions_Interest['solution_free'] =Solutions_Interest['solution']
lista
'''
for k in range(len(Solutions_Interest['solution'])):
  lista1 = Solutions_Interest['solution'][k]
  lista2 = Solutions_Interest['repeated'][k]
  l = []
  for i in lista1:
    for j in lista2:
      if i!=j:
        l.append(i)
        Solutions_Interest['solution_free'][k] = l
      else:
        continue
  '''

"\nfor k in range(len(Solutions_Interest['solution'])):\n  lista1 = Solutions_Interest['solution'][k]\n  lista2 = Solutions_Interest['repeated'][k]\n  l = []\n  for i in lista1:\n    for j in lista2:\n      if i!=j:\n        l.append(i)\n        Solutions_Interest['solution_free'][k] = l\n      else:\n        continue\n  "

In [20]:
for k in range(len(Solutions_Interest['solution'])):
  l = []
  lista1 = set(Solutions_Interest['solution'][k])
  lista2 = set(Solutions_Interest['repeated'][k])
  l.append(list(lista1-lista2))
  Solutions_Interest['solution_free'][k] = l[0]

<ipython-input-20-8a85160b1a19>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Solutions_Interest['solution_free'][k] = l[0]

In [21]:
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]","{'nu': 1, 's': 1.0}",[5]
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]","{'nu': 3, 's': 3.0}","[18, -10, -17]"
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]","{'nu': 3, 's': 3.0}","[8, -7]"
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]","{'nu': -11, 's': -11.0}","[8, 9, 2, 14]"
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]","{'nu': -19, 's': -19.0}","[16, 1, 18, 22]"
...,...,...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]","{'nu': -3, 's': -3.0}","[-26, -25, 7, 17, 18, -13, 29]"
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]","{'nu': 9, 's': 9.0}","[3, -24, -20, 12, 13, -8, 29]"
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]","{'nu': -24, 's': -24.0}","[19, 12, 13]"
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]","{'nu': -5, 's': -5.0}","[2, -27, -23, -18, 15, 21, 29]"
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]","{'nu': 27, 's': 27.0}","[-30, -26, -25, 14, -10]"

In [23]:
Solutions_Interest1_=Solutions_Interest.apply(lambda row: row['condition_model'].get('s'), axis='columns' )
Solutions_Interest['s'] = (Solutions_Interest1_)
Solutions_Interest

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s
0,"[-4, -2]","[5, 2]","[1, 1, 1, -4, -4, 5]",40,6,"[1, 1, -4]","{'nu': 1, 's': 1.0}",[5],1.0
1,"[-1, -3]","[-1, 8]","[3, 3, 3, -10, -17, 18]",18,6,"[3, 3]","{'nu': 3, 's': 3.0}","[18, -10, -17]",3.0
2,"[-1, -2]","[2, -1, 3]","[3, 3, 3, -5, -5, -7, 8]",6,7,"[3, 3, -5]","{'nu': 3, 's': 3.0}","[8, -7]",3.0
3,"[-3, 3]","[-3, 0, 2]","[2, 8, 9, -11, -11, -11, 14]",18,7,"[-11, -11]","{'nu': -11, 's': -11.0}","[8, 9, 2, 14]",-11.0
4,"[1, 0]","[-3, 3, -3]","[1, 16, 18, -19, -19, -19, 22]",9,7,"[-19, -19]","{'nu': -19, 's': -19.0}","[16, 1, 18, 22]",-19.0
...,...,...,...,...,...,...,...,...,...
304564,"[1, 5, 1, -7, -3]","[1, 9, 3, -9, 4]","[1, 1, -3, -3, -3, 7, -13, 17, 18, -25, -26, 29]",146,12,"[1, -3, -3]","{'nu': -3, 's': -3.0}","[-26, -25, 7, 17, 18, -13, 29]",-3.0
304565,"[-9, 0, -3, -6, 3]","[-3, -8, -9, -6, 5]","[3, -8, 9, 9, 9, 12, 13, -16, -16, -20, -24, 29]",54,12,"[9, 9, -16]","{'nu': 9, 's': 9.0}","[3, -24, -20, 12, 13, -8, 29]",9.0
304566,"[6, -9, 7, -9, 5]","[6, -6, 2, -3, 2]","[6, 6, 12, 13, 19, -21, -21, -24, -24, -24, 29...",176,12,"[6, -21, -24, -24, 29]","{'nu': -24, 's': -24.0}","[19, 12, 13]",-24.0
304567,"[8, -3, 1, -3, 4]","[-5, -3, -6, -9, 7]","[2, -5, -5, -5, 8, 8, 15, -18, 21, -23, -27, 29]",2,12,"[-5, -5, 8]","{'nu': -5, 's': -5.0}","[2, -27, -23, -18, 15, 21, 29]",-5.0
304568,"[2, 0, -3, -2, 2]","[9, -2, 9, 8, 4]","[6, 6, -8, -8, -10, 14, -25, -26, 27, 27, 27, ...",31,12,"[6, -8, 27, 27]","{'nu': 27, 's': 27.0}","[-30, -26, -25, 14, -10]",27.0

In [24]:
def Massless(x,s):
  if True:
    xx=x.copy()
    d= []
    if len(x)>0:
      for x in itertools.permutations(x,2):
        if x[0]<=x[1]:
          d.append(x)
    for j in d:
      if abs(sum(j))== abs(s):
        d.remove(j)
        j=list(j)
        for elements in j:
          if elements in xx:
            xx.remove(elements)

  return xx

In [25]:
Solutions_Interest['Massless']=Solutions_Interest.apply(lambda row: Massless(row['solution_free'], row['s']),axis="columns" )

In [26]:
Solution_Mass = Solutions_Interest[Solutions_Interest['Massless'].apply(lambda l: l==[] if isinstance(l,list) else False)].reset_index(drop=True)
Solution_Mass

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[-2, 0, 1]","[4, -4, 0, 4]","[1, 2, -4, -17, 21, 21, 21, -22, -23]",16,9,"[21, 21]","{'nu': 21, 's': 21.0}","[1, 2, -23, -22, -17, -4]",21.0,[]
1,"[-1, 0, 1]","[-1, -3, 0, 4]","[1, -3, 4, 9, 12, -13, -13, -13, 16]",2,9,"[-13, -13]","{'nu': -13, 's': -13.0}","[1, 4, 9, 12, 16, -3]",-13.0,[]
2,"[-4, 0, 4]","[-4, 2, 0, 1]","[1, -5, 10, 11, 20, -21, -21, -21, 26]",16,9,"[-21, -21]","{'nu': -21, 's': -21.0}","[1, 10, 11, 20, 26, -5]",-21.0,[]
3,"[6, 0, 3]","[-1, 1, 0, -1]","[1, 3, -6, -17, 23, 23, 23, -24, -26]",2,9,"[23, 23]","{'nu': 23, 's': 23.0}","[1, 3, -26, -24, -17, -6]",23.0,[]
4,"[2, -2, 2]","[-2, 0, -2, 5]","[1, 1, 9, 9, 9, -16, -19, -19, 25]",4,9,"[1, 9, 9, -19]","{'nu': 9, 's': 9.0}","[-16, 25]",9.0,[]
...,...,...,...,...,...,...,...,...,...,...
239,"[-1, 3, 4, -9, 6]","[-9, -6, 7, 4, -1]","[3, 3, 3, -9, 12, -15, -16, 19, -24, 25, 27, -28]",87,12,"[3, 3]","{'nu': 3, 's': 3.0}","[-28, -24, 12, -16, -15, 19, -9, 25, 27]",3.0,[]
240,"[3, -6, -7, -9, 1]","[-7, 3, -9, -6, 0]","[1, 6, 9, 9, 9, -10, -11, -15, 20, -21, -21, 24]",96,12,"[9, 9, -21]","{'nu': 9, 's': 9.0}","[1, 6, -15, 20, -11, -10, 24]",9.0,[]
241,"[-5, 0, 6, -2, -3]","[8, -2, 3, -1, 9]","[6, 7, 9, 9, 9, -14, -15, -16, -21, -21, 23, 24]",130,12,"[9, 9, -21]","{'nu': 9, 's': 9.0}","[6, 7, -16, -15, -14, 23, 24]",9.0,[]
242,"[4, -3, 0, -7, -2]","[9, 5, 3, -8, -6]","[2, 2, 2, -6, 8, -10, -16, 18, -19, 21, 23, -25]",12,12,"[2, 2]","{'nu': 2, 's': 2.0}","[-25, 8, -19, -16, 18, 21, -10, 23, -6]",2.0,[]
243,"[-9, 9, 3, -1, 2]","[5, 6, 3, 9, -7]","[3, 3, 3, -10, 13, -15, -16, -16, 18, 19, 19, ...",30,12,"[3, 3, -16, 19]","{'nu': 3, 's': 3.0}","[-21, 13, -15, 18, -10]",3.0,[]

In [27]:
Solution_MassFinal=Solution_Mass[Solution_Mass['repeated'].apply(len)==2].reset_index(drop=True)
Solution_MassFinal

,l,k,solution,gcd,n,repeated,condition_model,solution_free,s,Massless
0,"[-2, 0, 1]","[4, -4, 0, 4]","[1, 2, -4, -17, 21, 21, 21, -22, -23]",16,9,"[21, 21]","{'nu': 21, 's': 21.0}","[1, 2, -23, -22, -17, -4]",21.0,[]
1,"[-1, 0, 1]","[-1, -3, 0, 4]","[1, -3, 4, 9, 12, -13, -13, -13, 16]",2,9,"[-13, -13]","{'nu': -13, 's': -13.0}","[1, 4, 9, 12, 16, -3]",-13.0,[]
2,"[-4, 0, 4]","[-4, 2, 0, 1]","[1, -5, 10, 11, 20, -21, -21, -21, 26]",16,9,"[-21, -21]","{'nu': -21, 's': -21.0}","[1, 10, 11, 20, 26, -5]",-21.0,[]
3,"[6, 0, 3]","[-1, 1, 0, -1]","[1, 3, -6, -17, 23, 23, 23, -24, -26]",2,9,"[23, 23]","{'nu': 23, 's': 23.0}","[1, 3, -26, -24, -17, -6]",23.0,[]
4,"[3, 0, 3]","[5, 3, 5, 2]","[4, -6, 9, 10, 15, -19, -19, -19, 25]",6,9,"[-19, -19]","{'nu': -19, 's': -19.0}","[4, 9, 10, 15, 25, -6]",-19.0,[]
5,"[1, 0, 5]","[3, -3, -4, -1]","[1, 2, -5, -10, 15, 15, 15, -16, -17]",1,9,"[15, 15]","{'nu': 15, 's': 15.0}","[1, 2, -17, -16, -10, -5]",15.0,[]
6,"[1, 0, -1]","[1, 4, 0, 5]","[1, -4, 5, 16, 20, -21, -21, -21, 25]",2,9,"[-21, -21]","{'nu': -21, 's': -21.0}","[1, 5, 16, 20, 25, -4]",-21.0,[]
7,"[5, 0, -5]","[5, -2, 0, -4]","[2, -4, 5, 10, 13, -15, -15, -15, 19]",75,9,"[-15, -15]","{'nu': -15, 's': -15.0}","[2, 5, 10, 13, 19, -4]",-15.0,[]
8,"[-4, 0, 4]","[-4, -5, 0, -3]","[3, 4, -5, 21, 22, -25, -25, -25, 30]",32,9,"[-25, -25]","{'nu': -25, 's': -25.0}","[3, 4, 21, 22, -5, 30]",-25.0,[]
9,"[1, 0, -2]","[5, -5, 4, 5]","[4, -5, 7, 8, 11, -15, -15, -15, 20]",22,9,"[-15, -15]","{'nu': -15, 's': -15.0}","[4, 7, 8, 11, 20, -5]",-15.0,[]
10,"[-3, 0, 3]","[-3, -1, 0, 6]","[2, -6, 11, 12, 21, -23, -23, -23, 29]",18,9,"[-23, -23]","{'nu': -23, 's': -23.0}","[2, 11, 12, 21, -6, 29]",-23.0,[]
11,"[-1, 0, 1]","[-1, 6, 0, -3]","[5, -7, 8, 15, 18, -23, -23, -23, 30]",2,9,"[-23, -23]","{'nu': -23, 's': -23.0}","[5, 8, 15, 18, -7, 30]",-23.0,[]
12,"[6, 0, -6]","[6, 1, 0, 3]","[1, 4, -11, -12, 23, 23, 23, -24, -27]",72,9,"[23, 23]","{'nu': 23, 's': 23.0}","[1, 4, -27, -24, -12, -11]",23.0,[]
13,"[-3, 0, 5]","[-4, 4, 0, -4]","[1, -5, 7, 18, 24, -25, -25, -25, 30]",32,9,"[-25, -25]","{'nu': -25, 's': -25.0}","[1, 7, 18, 24, -5, 30]",-25.0,[]
14,"[-3, 0, 1]","[2, -2, 0, 2]","[1, -2, 3, 4, 6, -7, -7, -7, 9]",8,9,"[-7, -7]","{'nu': -7, 's': -7.0}","[1, 3, 4, 6, 9, -2]",-7.0,[]
15,"[1, -2, -3, 3]","[3, -1, 3, 0]","[1, 3, 3, 3, -4, -6, 9, -10, -12, 13]",6,10,"[3, 3]","{'nu': 3, 's': 3.0}","[1, 9, 13, -12, -10, -6, -4]",3.0,[]
16,"[-3, -1, -3, -1]","[-3, 0, 2, -1]","[3, 3, 3, 4, -6, -7, 9, -11, -12, 14]",6,10,"[3, 3]","{'nu': 3, 's': 3.0}","[4, 9, 14, -12, -11, -7, -6]",3.0,[]
17,"[1, 4, -4, 3]","[1, 0, 1, -2]","[1, 3, -4, -4, -4, 8, -12, 13, 16, -17]",6,10,"[-4, -4]","{'nu': -4, 's': -4.0}","[1, 3, 8, 13, -17, 16, -12]",-4.0,[]
18,"[-2, 5, 0, 3]","[1, 0, -3, 1]","[3, 5, 5, 5, -8, -10, 15, -17, -20, 22]",14,10,"[5, 5]","{'nu': 5, 's': 5.0}","[3, -20, 15, -17, -10, 22, -8]",5.0,[]
19,"[2, 4, 3, -2]","[-4, 0, 2, 3, -1]","[1, 2, 3, 3, 3, -4, -8, 11, -13, -14, 16]",2,11,"[3, 3]","{'nu': 3, 's': 3.0}","[1, 2, 11, 16, -14, -13, -8, -4]",3.0,[]
20,"[1, -3, -2, -1]","[1, 2, 1, 0, 4]","[2, -5, -5, -5, -7, 8, 12, -13, 16, 18, -21]",3,11,"[-5, -5]","{'nu': -5, 's': -5.0}","[2, 8, -21, 12, 16, 18, -13, -7]",-5.0,[]
21,"[-8, -2, 0, -10, 4]","[6, 4, 2, -2, 0]","[2, 2, 2, -6, -7, 8, 9, -10, 23, -24, -25, 26]",192,12,"[2, 2]","{'nu': 2, 's': 2.0}","[26, -25, 8, 9, -24, -10, 23, -7, -6]",2.0,[]
22,"[3, -4, 10, -8, 10]","[-9, 5, 0, 4, -5]","[3, 3, 3, -8, -9, 11, 12, -15, 17, -20, -21, 24]",70,12,"[3, 3]","{'nu': 3, 's': 3.0}","[11, 12, -20, -21, -15, 17, -9, -8, 24]",3.0,[]
23,"[5, -1, -8, -3, 3]","[-10, -8, 1, 10, -6]","[1, 1, 1, -3, 4, -5, -10, 11, -19, 20, 21, -22]",250,12,"[1, 1]","{'nu': 1, 's': 1.0}","[4, -22, 11, -19, 20, 21, -10, -5, -3]",1.0,[]
24,"[-1, 4, 3, 0, 4]","[-1, 0, -2, -3, -1]","[1, 1, 1, -3, 4, -5, -9, 10, -14, 15, 16, -17]",8,12,"[1, 1]","{'nu': 1, 's': 1.0}","[4, 10, 15, 16, -17, -14, -9, -5, -3]",1.0,[]
25,"[-2, 3, 2, -1, -3]","[-2, 1, 0, -3, 1]","[2, 2, 2, -6, 8, -10, -11, 13, -14, 15, 16, -17]",4,12,"[2, 2]","{'nu': 2, 's': 2.0}","[8, 13, 15, 16, -17, -14, -11, -10, -6]",2.0,[]
26,"[1, 0, 7, 6, -6]","[8, 7, -3, -2, 3]","[3, 3, 3, -9, 12, -13, -15, 16, 20, -21, -23, 24]",28,12,"[3, 3]","{'nu': 3, 's': 3.0}","[-23, -21, 12, 16, -15, -13, 20, -9, 24]",3.0,[]
27,"[4, 5, 1, -3, 5]","[3, 4, 0, 5, -8]","[1, 3, 4, 4, 4, -12, 13, 16, -17, -20, -24, 28]",96,12,"[4, 4]","{'nu': 4, 's': 4.0}","[1, 3, -24, -20, 13, -17, 16, -12, 28]",4.0,[]
28,"[1, 4, -3, -6, -8]","[1, 9, -2, 5, -7]","[2, -3, -3, -3, -5, 10, -13, 15, -18, 21, 23, ...",51,12,"[-3, -3]","{'nu': -3, 's': -3.0}","[2, -26, 10, -18, 15, -13, 21, 23, -5]",-3.0,[]
29,"[-4, -9, -1, 5, 6]","[3, -9, -6, 8, 6]","[3, 3, 3, -4, 7, -9, 11, 12, -14, -15, -18, 21]",57,12,"[3, 3]","{'nu': 3, 's': 3.0}","[7, 11, 12, -18, -15, -14, 21, -9, -4]",3.0,[]
30,"[-6, -4, 2, 0, -2]","[-1, -3, -4, -5, 7]","[3, 3, 3, -5, 8, -14, -15, 17, 18, -20, -21, 23]",32,12,"[3, 3]","{'nu': 3, 's': 3.0}","[8, -21, -20, -15, -14, 17, 18, 23, -5]",3.0,[]
31,"[-6, 5, -3, 3, 5]","[-4, -6, -3, -7, -6]","[3, 3, 3, -5, 8, -9, 12, -15, 23, -26, -27, 30]",138,12,"[3, 3]","{'nu': 3, 's': 3.0}","[-27, -26, 8, 12, -15, 23, -9, -5, 30]",3.0,[]
32,"[1, 6, 0, -6, 2]","[4, 1, 5, 1, -4]","[1, -3, -3, -3, -4, 9, -10, -12, 13, 15, 18, -21]",9,12,"[-3, -3]","{'nu': -3, 's': -3.0}","[1, 9, -21, 13, 15, 18, -12, -10, -4]",-3.0,[]
33,"[1, 3, 1, 0, 6]","[-5, 7, 8, -4, 1]","[3, 3, 3, -9, -11, 12, 14, -15, 22, -24, -25, 27]",21,12,"[3, 3]","{'nu': 3, 's': 3.0}","[-25, -24, 12, 14, -15, -11, 22, -9, 27]",3.0,[]
34,"[6, -4, 3, -1, 7]","[-1, -3, 6, -6, -5]","[3, 3, 3, -8, 11, -13, -14, 15, 16, -18, -19, 21]",28,12,"[3, 3]","{'nu': 3, 's': 3.0}","[11, -19, -18, 15, 16, -14, -13, 21, -8]",3.0,[]
35,"[-1, 3, 4, -9, 6]","[-9, -6, 7, 4, -1]","[3, 3, 3, -9, 12, -15, -16, 19, -24, 25, 27, -28]",87,12,"[3, 3]","{'nu': 3, 's': 3.0}","[-28, -24, 12, -16, -15, 19, -9, 25, 27]",3.0,[]
36,"[4, -3, 0, -7, -2]","[9, 5, 3, -8, -6]","[2, 2, 2, -6, 8, -10, -16, 18, -19, 21, 23, -25]",12,12,"[2, 2]","{'nu': 2, 's': 2.0}","[-25, 8, -19, -16, 18, 21, -10, 23, -6]",2.0,[]